### ISSUE TITLE
Annotation mistake in Tutorial.ipynb

### ISSUE THREAD

**Issue by yyccli** [hyperledger/fabric-sdk-py#107]
Hi
There is a little mistake in Tutorial.ipynb. Above block [5], the annotation says **Run the below code snippet to make the peers of Org1 join the channel.** Actually, block [5] adds peers of **Org2** into the channel.

:smiley:

**Comment by dexhunter** [comment]
cc @RohanShrothrium

**Comment by dexhunter** [comment]
solved #111
