### ISSUE TITLE
Unable invoke and query the chaincode through the Gateway 

### ISSUE THREAD

**Issue by leptdre** [hyperledger/fabric-sdk-py#116]
I came through an issue where I want to evaluate a transaction in a chaincode, however, the code `fabric-sdk-py/hfc/fabric_network/contract.py` seems broken at the `evaluate_transaction` function: 

```
    async def evaluate_transaction(self, **name**, args, requestor):
        channel_name = self.network.**channel3**
        cli = self.gatetway.client
        peers = cli._peers

        response = await cli.chaincode_query(requestor=requestor,
                                             channel_name=channel_name,
                                             peers=peers,
                                             args=args,
                                             cc_name=self.cc_name)
        return response
```
The first issue is with the `channel3` variable which doesn't exist. The second issue is with `name`argument of the `evaluate_transaction` function which seems no not be used. 
Could you please check?

**Comment by RohanShrothrium** [comment]
The usage of the contract class for invocation can be found [https://github.com/hyperledger/fabric-sdk-py/blob/master/docs/source/tutorial.md](here).
Yes, I believe channel_name should be `self.network.channel` which is a typo.
Evaluate transaction is used for querying the ledger, for more details on how to use it you can check out the above link.
Hope this helps!
