### ISSUE TITLE
How to transfer or change an asset on the ledger?

### ISSUE THREAD

**Issue by PetrMixayloff** [hyperledger/fabric-sdk-py#117]
Hi, I'm studying hyperledger fabric and have read this [tutorial](https://fabric-sdk-py.readthedocs.io/en/latest/tutorial.html).
Can you tell what about exchanging assets? How can I do a new transaction in network?

**Comment by h0rs3fa11** [comment]
You need to install and instantiate a chaincode, and invoke it to send a new transaction.

**Comment by PetrMixayloff** [comment]
> You need to install and instantiate a chaincode, and invoke it to send a new transaction.

Thank you for answer. But it is not actual now for me. Since I asked question we have done this job on node js sdk. The official documentation turned out to be more understandable for me, even the fact that I don't know the node js very well
