### ISSUE TITLE
Can the CA of the network profile become optional?

### ISSUE THREAD

**Issue by h0rs3fa11** [hyperledger/fabric-sdk-py#123]
Some test networks don't have the CA. To execute the SDK test, you must comment the code that loads the CA configuration first 
```python
# Init CAs
cas = self.get_net_info('certificateAuthorities')
for name in cas:
    _logger.debug("create ca with name={}".format(name))
     ca = create_ca(name, cas[name])
     self._CAs[name] = ca
```

**Comment by dexhunter** [comment]
I think CA currently is optional. Some tests require CA configuration while some do not.
