### ISSUE TITLE
Problem creating channel in python tutorial

### ISSUE THREAD

**Issue by harredon01** [hyperledger/fabric-sdk-py#135]
Hello. I am having trouble running the python sdk example to create a channel with the default values. I have already added the binaries to my path, etc. 

This is the code I am running within the fabric-sdk-py folder:
import asyncio
from hfc.fabric import Client
loop = asyncio.get_event_loop()

cli = Client(net_profile="test/fixtures/network.json")
print(cli.organizations)  # orgs in the network
print(cli.peers)  # peers in the network
print(cli.orderers)  # orderers in the network
print(cli.CAs)  # ca nodes in the network

org1_admin = cli.get_user(org_name='org1.example.com', name='Admin')

# Create a New Channel, the response should be true if succeed
response = loop.run_until_complete(cli.channel_create(
            orderer='orderer.example.com',
            channel_name='businesschannel',
            requestor=org1_admin,
            config_yaml='test/fixtures/e2e_cli/',
            channel_profile='TwoOrgsChannel'
            ))
print(response == True)

And the error I am getting is:
Init client with profile=test/fixtures/network.json
create org with name=orderer.example.com
create org with name=org1.example.com
create org with name=org2.example.com
create ca with name=ca-org1
create ca with name=ca-org2
Import orderers = dict_keys(['orderer.example.com'])
Import peers = dict_keys(['peer0.org1.example.com', 'peer1.org1.example.com', 'peer0.org2.example.com', 'peer1.org2.example.com'])
{'orderer.example.com': <hfc.fabric.organization.Organization object at 0x7f7d1a9d9a60>, 'org1.example.com': <hfc.fabric.organization.Organization object at 0x7f7d1cebadf0>, 'org2.example.com': <hfc.fabric.organization.Organization object at 0x7f7d1ced5e50>}
{'peer0.org1.example.com': <hfc.fabric.peer.Peer object at 0x7f7d1ced5760>, 'peer1.org1.example.com': <hfc.fabric.peer.Peer object at 0x7f7d1ced5280>, 'peer0.org2.example.com': <hfc.fabric.peer.Peer object at 0x7f7d1ced5eb0>, 'peer1.org2.example.com': <hfc.fabric.peer.Peer object at 0x7f7d1a68c790>}
{'orderer.example.com': <hfc.fabric.orderer.Orderer object at 0x7f7d1ced56a0>}
{'ca-org1': <hfc.fabric.certificateAuthority.certificateAuthority object at 0x7f7d1ced5d60>, 'ca-org2': <hfc.fabric.certificateAuthority.certificateAuthority object at 0x7f7d1ced5a60>}
FABRIC_CFG_PATH set to /home/hoovert/fabric-sdk-py/test/fixtures/e2e_cli/
--- Logging error ---
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/logging/__init__.py", line 1079, in emit
    msg = self.format(record)
  File "/usr/local/lib/python3.9/logging/__init__.py", line 923, in format
    return fmt.format(record)
  File "/usr/local/lib/python3.9/logging/__init__.py", line 659, in format
    record.message = record.getMessage()
  File "/usr/local/lib/python3.9/logging/__init__.py", line 363, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/home/hoovert/fabric-sdk-py/test1.py", line 16, in <module>
    response = loop.run_until_complete(cli.channel_create(
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 629, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 596, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1890, in _run_once
    handle._run()
  File "/usr/local/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/hoovert/fabric-sdk-py/hfc/fabric/client.py", line 505, in channel_create
    tx = self.generate_channel_tx(channel_name, config_yaml,
  File "/home/hoovert/fabric-sdk-py/hfc/fabric/client.py", line 1117, in generate_channel_tx
    _logger.error('Failed to generate transaction file', err)
Message: 'Failed to generate transaction file'
Arguments: (b'\x1b[34m2021-02-23 16:39:18.006 -05 [common.tools.configtxgen] main -> INFO 001\x1b[0m Loading configuration\n\x1b[34m2021-02-23 16:39:18.010 -05 [common.tools.configtxgen.localconfig] Load -> INFO 002\x1b[0m Loaded configuration: /home/hoovert/fabric-sdk-py/test/fixtures/e2e_cli/configtx.yaml\n\x1b[34m2021-02-23 16:39:18.010 -05 [common.tools.configtxgen] doOutputChannelCreateTx -> INFO 003\x1b[0m Generating new channel configtx\n\x1b[35m2021-02-23 16:39:18.010 -05 [common.tools.configtxgen] main -> FATA 004\x1b[0m Error on outputChannelCreateTx: could not generate default config template: error parsing configuration: error adding policies to channel group: no policies defined\n',)
Configtx is empty
False

Any help greatly appreciated.

**Comment by dexhunter** [comment]
```
Configtx is empty
False
```
The error still looks like the binaries are not included

**Comment by milan-15697** [comment]
Hello, can you share the solution for the above problem. I am getting the same error while trying to create channel via py sdk.

**Comment by dexhunter** [comment]
Hi @milan-15697 the solution is to include the binaries in the PATH. You can try to `echo $PATH` to verify if the binaries are included.

**Comment by milan-15697** [comment]
Hi @dexhunter, thanks for the revert. Below is the output of the values in PATH, can you tell me how can I link the binaries? I am still new to this.

`/Users/milan/anaconda3/bin:/Users/milan/anaconda3/condabin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/opt/X11/bin:/Library/Apple/usr/bin`

Many Thanks

**Comment by milan-15697** [comment]
Hey, I downloaded and added the binaries to the PATH, still having the same issue, I have attached the executed commands for reference. As you can see the first part of PATH has the path to bin under fabric-samples. Second command ls verifies the same. When I run t1.py which contains below code, I get the below error:

```
(base) milan@Milans-MBP fabric-sdk-py % echo $PATH
/Users/milan/Documents/hfl/fabric-samples/bin:/Users/milan/anaconda3/bin:/Users/milan/anaconda3/condabin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/opt/X11/bin:/Library/Apple/usr/bin
(base) milan@Milans-MBP fabric-sdk-py % ls /Users/milan/Documents/hfl/fabric-samples/bin
configtxgen		configtxlator		cryptogen		discover		fabric-ca-client	fabric-ca-server	ledgerutil		orderer			osnadmin		peer
```
Code:
```

import asyncio
from hfc.fabric import Client

loop = asyncio.get_event_loop()

cli = Client(net_profile="test/fixtures/network.json")
org1_admin = cli.get_user(org_name='org1.example.com', name='Admin')

# Create a New Channel, the response should be true if succeed
response = loop.run_until_complete(cli.channel_create(
            orderer='orderer.example.com',
            channel_name='businesschannel',
            requestor=org1_admin,
            config_yaml='test/fixtures/e2e_cli/configtx.yaml',
            channel_profile='TwoOrgsChannel'
            ))
print(response == True)
```
```
(base) milan@Milans-MBP fabric-sdk-py % python t1.py
Init client with profile=test/fixtures/network.json
create org with name=orderer.example.com
create org with name=org1.example.com
create org with name=org2.example.com
create ca with name=ca-org1
create ca with name=ca-org2
Import orderers = dict_keys(['orderer.example.com'])
Import peers = dict_keys(['peer0.org1.example.com', 'peer1.org1.example.com', 'peer0.org2.example.com', 'peer1.org2.example.com'])
FABRIC_CFG_PATH set to /Users/milan/Documents/hfl/fabric-sdk-py/test/fixtures/e2e_cli/configtx.yaml
--- Logging error ---
Traceback (most recent call last):
  File "/Users/milan/anaconda3/lib/python3.8/logging/__init__.py", line 1081, in emit
    msg = self.format(record)
  File "/Users/milan/anaconda3/lib/python3.8/logging/__init__.py", line 925, in format
    return fmt.format(record)
  File "/Users/milan/anaconda3/lib/python3.8/logging/__init__.py", line 664, in format
    record.message = record.getMessage()
  File "/Users/milan/anaconda3/lib/python3.8/logging/__init__.py", line 369, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "t1.py", line 10, in <module>
    response = loop.run_until_complete(cli.channel_create(
  File "/Users/milan/anaconda3/lib/python3.8/asyncio/base_events.py", line 603, in run_until_complete
    self.run_forever()
  File "/Users/milan/anaconda3/lib/python3.8/asyncio/base_events.py", line 570, in run_forever
    self._run_once()
  File "/Users/milan/anaconda3/lib/python3.8/asyncio/base_events.py", line 1859, in _run_once
    handle._run()
  File "/Users/milan/anaconda3/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/Users/milan/Documents/hfl/fabric-sdk-py/hfc/fabric/client.py", line 505, in channel_create
    tx = self.generate_channel_tx(channel_name, config_yaml,
  File "/Users/milan/Documents/hfl/fabric-sdk-py/hfc/fabric/client.py", line 1117, in generate_channel_tx
    _logger.error('Failed to generate transaction file', err)
Message: 'Failed to generate transaction file'
Arguments: (b'\x1b[34m2024-02-01 17:39:43.759 CET 0001 INFO\x1b[0m [common.tools.configtxgen] \x1b[34;1mmain\x1b[0m -> Loading configuration\n\x1b[31m2024-02-01 17:39:43.761 CET 0002 ERRO\x1b[0m [viperutil] \x1b[31;1mReadInConfig\x1b[0m -> Unable to open the config file: \n\x1b[35m2024-02-01 17:39:43.762 CET 0003 PANI\x1b[0m [common.tools.configtxgen.localconfig] \x1b[35;1mLoad\x1b[0m -> Error reading configuration: open : no such file or directory\n\x1b[35m2024-02-01 17:39:43.762 CET 0004 PANI\x1b[0m [common.tools.configtxgen] \x1b[35;1mfunc1\x1b[0m -> Error reading configuration: open : no such file or directory\npanic: Error reading configuration: open : no such file or directory [recovered]\n\tpanic: Error reading configuration: open : no such file or directory\n\ngoroutine 1 [running]:\ngo.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc0002b63c0, {0x0, 0x0, 0x0})\n\t/home/runner/work/fabric/fabric/vendor/go.uber.org/zap/zapcore/entry.go:232 +0x44c\ngo.uber.org/zap.(*SugaredLogger).log(0xc0001a1d48, 0x4, {0xc00019cec0?, 0x30?}, {0x0?, 0xc00019ce80?, 0xc000197450?}, {0x0, 0x0, 0x0})\n\t/home/runner/work/fabric/fabric/vendor/go.uber.org/zap/sugar.go:227 +0xee\ngo.uber.org/zap.(*SugaredLogger).Panicf(...)\n\t/home/runner/work/fabric/fabric/vendor/go.uber.org/zap/sugar.go:159\ngithub.com/hyperledger/fabric/common/flogging.(*FabricLogger).Panic(0xc0001a1d50?, {0xc0002ad9c0?, 0x175e63b?, 0x16?})\n\t/home/runner/work/fabric/fabric/common/flogging/zap.go:73 +0x5d\nmain.main.func1()\n\t/home/runner/work/fabric/fabric/cmd/configtxgen/main.go:261 +0x1b1\npanic({0x1646320, 0xc0001f7fe0})\n\t/opt/hostedtoolcache/go/1.20.6/x64/src/runtime/panic.go:884 +0x213\ngo.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc0002b63c0, {0x0, 0x0, 0x0})\n\t/home/runner/work/fabric/fabric/vendor/go.uber.org/zap/zapcore/entry.go:232 +0x44c\ngo.uber.org/zap.(*SugaredLogger).log(0xc0001a1d28, 0x4, {0x1765dda?, 0x15?}, {0xc0002addb0?, 0x15eacdb?, 0x198c343?}, {0x0, 0x0, 0x0})\n\t/home/runner/work/fabric/fabric/vendor/go.uber.org/zap/sugar.go:227 +0xee\ngo.uber.org/zap.(*SugaredLogger).Panicf(...)\n\t/home/runner/work/fabric/fabric/vendor/go.uber.org/zap/sugar.go:159\ngithub.com/hyperledger/fabric/common/flogging.(*FabricLogger).Panicf(...)\n\t/home/runner/work/fabric/fabric/common/flogging/zap.go:74\ngithub.com/hyperledger/fabric/internal/configtxgen/genesisconfig.Load({0x7ff7bfeff806, 0xe}, {0xc0002adf48, 0x1, 0x1760320?})\n\t/home/runner/work/fabric/fabric/internal/configtxgen/genesisconfig/config.go:238 +0x1c8\nmain.main()\n\t/home/runner/work/fabric/fabric/cmd/configtxgen/main.go:277 +0x845\n',)
Configtx is empty
False
```

Hope we can ignore the TypeError for now

**Comment by dexhunter** [comment]
> Hope we can ignore the TypeError for now

Hmm... I don't think this is the issue. Just want to double check on which version of fabric are you using? Currently only `1.4` is supported so need to use [this binary](https://hyperledger-fabric.readthedocs.io/en/release-1.4/build_network.html) I just tested and working fine. I'll update the descriptions. For now, you can download the binary [here](https://github.com/hyperledger/fabric/releases/download/v1.4.12/hyperledger-fabric-darwin-amd64-1.4.12.tar.gz) 

<img width="1504" alt="Screenshot 2024-02-05 at 6 03 09 PM" src="https://github.com/hyperledger/fabric-sdk-py/assets/6930518/3bcda717-e4c1-41f5-9df2-6af56d5ac75e">

I will work on bridging the latest fabric to sdk.
