### ISSUE TITLE
Addition of pre-commit

### ISSUE THREAD

**Issue by shubhank-saxena** [hyperledger/fabric-sdk-py#142]
@dexhunter 
Since this repo contains python code, I thought maybe we can have a sort of rule check in the form of pre-commit config, which can help us maintain the code quality before someone raises a PR. The already existing lint test configurations can be used for having a pre-commit.
If it's something that you feel we can add, please let me know. I can work on this!
Thank you!

**Comment by dexhunter** [comment]
I think we already have this feature, you can check the config [here](https://github.com/hyperledger/fabric-sdk-py/blob/main/tox.ini)
