### ISSUE TITLE
400 when invoking chaincode using tutorial 

### ISSUE THREAD

**Issue by rcpurdue** [hyperledger/fabric-sdk-py#163]
Hi, I'm just trying to get the tutorial code running. It errors with  "response" of "400" when invoking the example chaincode. 

I'm running on an Ubuntua 20.04 server. All of the containers seem to start up correctly. The "TLDR" quick test returns "...1 passed, 12 warnings...py3: commands succeeded...congratulations...". 

My code, [tutorial.py](https://github.com/hyperledger/fabric-sdk-py/files/8428500/tutorial.txt), is copied from https://fabric-sdk-py.readthedocs.io/en/latest/tutorial.html. (I was going to use the code from Tutorial.ipynb, but it seems to be missing code to define "loop".)  I haven't modified the tutorial code other than to place it in one script, move the imports to the top, add comments, and print outputs. 

Please help with any hints or advice. I've spent days trying to get this working. Thank you!  

Rob Campbell
Research Computing
Purdue University

**Comment by RohanShrothrium** [comment]
Hi @rcpurdue!
Do all the steps till invoking the chaincode work without any errors?

**Comment by rcpurdue** [comment]
Hi RohanShrothrium! Yes, I think the previous steps work correctly. Here's the [full output](https://github.com/hyperledger/fabric-sdk-py/files/8428954/output.txt). Thank you for looking at this,   - Rob

**Comment by RohanShrothrium** [comment]
Hi @rcpurdue!
The chaincode response is `400` so it isn't the error.
The error is thrown at the upgrade stage, this error is thrown as the current chaincode is at v1.0 and you are trying to update it as you can see in your error log that says `RuntimeError: version already exists for chaincode with name 'example_cc'`.

**Comment by rcpurdue** [comment]
Hi @RohanShrothrium, 
Doh! I see now - the "400" isn't an error code. It is the result of 'b' having 300 and 'a' contributing 100. How embarrassing! Thank you so much for your help. I won't worry about the upgrade error as I'm more interested in chaincode invocation and query.  Thanks again,  - Rob
