### ISSUE TITLE
"configtxgen not in PATH. Configtx is empty" if anyone can help me? thanks

### ISSUE THREAD

**Issue by Creazy-MR** [hyperledger/fabric-sdk-py#165]
when i test the SDK linke this: tox -e py3 -- test/integration/e2e_test.py 
i have a error:
    
E2E testing started...
New channel with name = testchainid
E2E: Get channel testchainid config start
E2E: Get channel testchainid config done
E2E: Channel creation start: name=businesschannel
configtxgen not in PATH.
Configtx is empty
tear down
F

my configtxgen have been setting in gopath, i need help ,thx

**Comment by yeasy** [comment]
Install steps are at https://hlf.readthedocs.io/en/release-2.2/install.html.

**Comment by Creazy-MR** [comment]
@yeasy thak you very much

**Comment by Creazy-MR** [comment]
@yeasy  Dear developer, thanks your help, but i have join the configtxgen to the PATH, it still not work, i will  try to re-install it,thank you agin!
![error2](https://user-images.githubusercontent.com/59354418/168194340-2928bc60-2d3f-4d84-8d64-c10c9e5aae96.png)

**Comment by Creazy-MR** [comment]
@yeasy Dear developer,i have re-install the Fabric to v2.2, and setting the bin to the PATH,but it still didn‘t work , I am very distressed. thanks for your advices and helps！
![image](https://user-images.githubusercontent.com/59354418/168217332-19fa9714-1c3b-4672-af10-18495c6d55e2.png)

**Comment by Creazy-MR** [comment]
![image](https://user-images.githubusercontent.com/59354418/168253379-b93ca1a8-0384-4142-8022-c2ef96cfa1bf.png)
Thanks for timely reply，dear professor an developer，i finally find in my fabric-sdk-py/hfc/fabric/client.py ,shutil.which()can not find the configtxgen,but i have add it to my PATH. i still don't kown why.

**Comment by Creazy-MR** [comment]
Thanks for timely reply，dear professor an developer，i finally find in my fabric-sdk-py/hfc/fabric/client.py ,shutil.which()can not find the configtxgen,but i have add it to my PATH. i still don't kown why.
![image](https://user-images.githubusercontent.com/59354418/168254234-5ea33e10-67cb-450d-952a-97e66d7c4a95.png)

**Comment by Creazy-MR** [comment]
when i try to setting  os.environ["PATH"]='<mybash path>',it work! but i still have this error:
![image](https://user-images.githubusercontent.com/59354418/168264056-5307dcea-2ebf-45c8-8e11-377d49fb9080.png)

**Comment by Creazy-MR** [comment]
i don't know why its always set up a 1.4.6 peer..........
![image](https://user-images.githubusercontent.com/59354418/168264324-4e4460eb-0359-420f-80c6-2a45b38180f0.png)
