### ISSUE TITLE
dear developer, if i want  orderer node to do more tasks,what should i do ,thanks!

### ISSUE THREAD

**Issue by Creazy-MR** [hyperledger/fabric-sdk-py#166]
Dear developer:
      thanks for your efforts on this Python SDK.recently,i want use Fabric Python SDK to do more applications. but i need orderer nodes to  do more tasks before committing the block to the world state. How can i do with Python SDK,.

**Comment by yeasy** [comment]
The orderer logic is in the fabric repo: https://github.com/hyperledger/fabric/. You may take a look at the code there.

**Comment by Creazy-MR** [comment]
@yeasy thanks!
