### ISSUE TITLE
configtxgen not in PATH

### ISSUE THREAD

**Issue by jmreddy2106** [hyperledger/fabric-sdk-py#179]
Hi, I've set the fabric python SDK and running the Docker images. While running the sample notebook, it raises an error `configtxgen not in PATH. Configtx is empty`. I have set the path for configtxgen from fabric-samples/bin to FABRIC_CFG_PATH. Any idea, why it is throwing error? 

Thank you

**Comment by yeasy** [comment]
Copy the bins to one of your env path, e.g., /usr/local/bin.
