### ISSUE TITLE
Mentorship Program 2020

### ISSUE THREAD

**Issue by dexhunter** [hyperledger/fabric-sdk-py#42]
Dear Potential Mentees,

Hi, thank you for your interest in the fabric-sdk-py project. Our current priority is to add features supporting Fabric 1.4.x. You can take a reference from nodejs/golang sdk (release-1.4). To make you more competitive in the application process, you are advised to make contributions to the codebase. You can fix typos/urls, report a bug, add a feature and other contributions towards the project. You are also encouraged to join [our rocketchat](https://chat.hyperledger.org) via channel `#fabric-sdk-py`. If there are any other issues you want to ask, feel free to comment on this thread.

Some resources:

* [How to apply](https://wiki.hyperledger.org/display/INTERN/How+to+Apply)
* [mentorship program wiki](https://wiki.hyperledger.org/display/INTERN/Hyperledger+Mentorship+Program)
* [fabric-sdk-py wikil](https://fabric-sdk-py.readthedocs.io/)

Kind Regards,
Dixing (Dex) Xu

**Comment by yeasy** [comment]
@dexhunter hopefully, we can finish the experimental support for HLF v2.0 too, if the intern program is 6-month.

**Comment by Fierozen** [comment]
How far along is the "experimental support for HLF v2.0"? Is it in a particular branch? Is there a "roadmap" document about how it is developing? which features have been worked on?

**Comment by yeasy** [comment]
We hope that sdk-py can support HLF v1.4 and v2.0 at the same time.
The HLF v1.4 supports (current work) will be mature enough for production usage, with enough test cases and documentations.

**Comment by viragumathe5** [comment]
Is the order and questions for the Cover Letter are fixed?? 
Can we add something extra like the process of execution of the project or rough timeline or ideas about the project etc. in the cover letter???

**Comment by Dhiraj240** [comment]
Can we get this project working on windows 8.1?

**Comment by dexhunter** [comment]
> Can we get this project working on windows 8.1?

If you can install docker on windows 8.1 you might have a chance to make it work.

**Comment by dexhunter** [comment]
> Is the order and questions for the Cover Letter are fixed??
Can we add something extra like the process of execution of the project or rough timeline or ideas about the project etc. in the cover letter???

These are prerequisites, you need to ask at #mentorship-program of rocket chat.

**Comment by viragumathe5** [comment]
@dexhunter can we ask out project mentors to review our application???

**Comment by Zircoz** [comment]
Was anyone selected for this program yet?

**Comment by dexhunter** [comment]
@Zircoz Not yet. I will report top3 candidate list to Hyperledger around May.14th (May.15th is the deadline)

**Comment by viragumathe5** [comment]
Is the interview is not a compulsory task for all projects??
Like some participants are completed with their interview process while some are not???
