### ISSUE TITLE
unable to use "first-network" network.json file with python sdk

### ISSUE THREAD

**Issue by mothukuriv** [hyperledger/fabric-sdk-py#56]
create org with name=Org1
create ca with name=ca.org1.fabricfl.com
No key path ('orderers',) exists in net info
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/viraajimothukuri/fabric-sdk-py/hfc/fabric/client.py", line 76, in __init__
    self.init_with_net_profile(net_profile)
  File "/Users/viraajimothukuri/fabric-sdk-py/hfc/fabric/client.py", line 116, in init_with_net_profile
    _logger.debug("Import orderers = {}".format(orderers.keys()))
AttributeError: 'NoneType' object has no attribute 'keys'

**Comment by RohanShrothrium** [comment]
Hey @mothukuriv!
Please checkout the format of the `network.json` file as mentioned in `test/fixtures/network.json`. 
According to the error you are getting, I believe there are `orderers` has not been mentioned in your `network.json` file!

**Comment by dexhunter** [comment]
@mothukuriv Did you start docker services?

**Comment by mothukuriv** [comment]
Sorry.. I didnt get notification for replies.... I m using network.json file which is auto generated by byfn.sh script in "first-network" folder.

**Comment by mothukuriv** [comment]
> @mothukuriv Did you start docker services?

yes ...

**Comment by mothukuriv** [comment]
> Hey @mothukuriv!
> Please checkout the format of the `network.json` file as mentioned in `test/fixtures/network.json`.
> According to the error you are getting, I believe `orderers` has not been mentioned in your `network.json` file!

do we have any script which can generate network.json file ? 
I have used the suggested one it is still failing with below error

Message: 'Failed to generate transaction file'
Arguments: (b'\x1b[34m2020-04-17 00:46:34.883 EDT [common.tools.configtxgen] main -> INFO 001\x1b[0m Loading configuration\n\x1b[34m2020-04-17 00:46:34.894 EDT [common.tools.configtxgen.localconfig] Load -> INFO 002\x1b[0m Loaded configuration: /##/##/fabric-sdk-py/test/fixtures/e2e_cli/configtx.yaml\n\x1b[34m2020-04-17 00:46:34.894 EDT [common.tools.configtxgen] doOutputChannelCreateTx -> INFO 003\x1b[0m Generating new channel configtx\n\x1b[35m2020-04-17 00:46:34.894 EDT [common.tools.configtxgen] main -> FATA 004\x1b[0m Error on outputChannelCreateTx: could not generate default config template: error parsing configuration: error adding policies to channel group: no policies defined\n',)
Configtx is empty

FABRIC_CFG_PATH is set to configtx file

**Comment by dexhunter** [comment]
You need to include binaries in the PATH
