### ISSUE TITLE
Add CODE_OF_CONDUCT.md file 

### ISSUE THREAD

**Issue by viragumathe5** [hyperledger/fabric-sdk-py#62]
Add code of conduct for this repository plz take help of [this](https://wiki.hyperledger.org/display/HYP/Hyperledger+Code+of+Conduct)

**Comment by dexhunter** [comment]
We do have a [contributing guidelines](https://github.com/hyperledger/fabric-sdk-py/blob/master/CONTRIBUTING.md). I think this serves as code of conduct.
