### ISSUE TITLE
Python Coding Style should be improved for the fabric-sdk-py

### ISSUE THREAD

**Issue by viragumathe5** [hyperledger/fabric-sdk-py#63]
There must be a trace from Coding Guidelines for Fabric in Coding Style documentation

**Comment by viragumathe5** [comment]
@dexhunter if you think this issue is necessary I want to work on it 
Will you please give me your views over this

**Comment by viragumathe5** [comment]
I am sorry for late reply @dexhunter 
fabric-sdk-py is the python SDK for fabric but for that, we have our python documentation available but there is no fabric documentation in the repository for coding style. 
No, this is not at all related to the #40

**Comment by dexhunter** [comment]
Hmm... Fabric and Fabric SDK are separated. For Fabric Documentation, you
will submit on a different repo. (hyperledger/fabric rather than
hyperledger/fabric-sdk-py)

**Comment by viragumathe5** [comment]
ok
