### ISSUE TITLE
local test failed for couchdbwalletstore

### ISSUE THREAD

**Issue by dexhunter** [hyperledger/fabric-sdk-py#76]
For Azure pipelines, I've made an external service for couchdb, but locally the build will fail if I do not install couchdb manually. I think we should use a docker instance for a local couchdbwalletstore test as well. 
![image](https://user-images.githubusercontent.com/6930518/81385540-125c5280-9146-11ea-86b8-0c21bb828877.png)

**Comment by dexhunter** [comment]
cc @RohanShrothrium

**Comment by RohanShrothrium** [comment]
We have included CouchDB in the `requirements.txt`. Shouldn't this be enough?
I think the port isn't open hence it is giving a `ConnectionRefused` error.

**Comment by dexhunter** [comment]
> We have included CouchDB in the requirements.txt. Shouldn't this be enough?

This is only for python usage. You still need to start a coudb server instance.

**Comment by RohanShrothrium** [comment]
> This is only for python usage. You still need to start a coudb server instance.
Okay, I get it! So do you suggest installing CouchDB in the make file while installing or start an instance via docker?

**Comment by dexhunter** [comment]
via docker

**Comment by RohanShrothrium** [comment]
Okay will work on this!
