### ISSUE TITLE
Channel created fail

### ISSUE THREAD

**Issue by znss1989** [hyperledger/fabric-sdk-py#81]
Hello, I was following the tutorial of the Fabric Python SDK.

First I set up the network with the commands given. 

```bash
export HLF_VERSION=1.4.0
docker pull hyperledger/fabric-peer:${HLF_VERSION} \
    && docker pull hyperledger/fabric-orderer:${HLF_VERSION} \
    && docker pull hyperledger/fabric-ca:${HLF_VERSION} \
    && docker pull hyperledger/fabric-ccenv:${HLF_VERSION}
docker-compose -f test/fixtures/docker-compose-2orgs-4peers-tls.yaml up
```

Then I tried to create a channel and join a peer like the following.

```python
async def async_main():
    cli = Client(net_profile=CONNECTION_PROFILE_PATH)

    print(cli.organizations) # orgs in the network
    print(cli.peers) # peers in the network
    print(cli.orderers) # orderers in the network
    print(cli.CAs) # ca nodes in the network

    # get the admin user from local path
    org1_admin = cli.get_user(org_name='org1.example.com', name='Admin')

    # Create a New Channel, the response should be true if succeed
    response = await cli.channel_create(
        orderer='orderer.example.com',
        channel_name='businesschannel',
        requestor=org1_admin,
        config_yaml=CONFIG_YAML_PATH,
        channel_profile='TwoOrgsChannel'
    )
    if response:
        print("Create channel successful")
    else:
        print("Create channel failed")
        print(response)
        exit(-1)

    # Join Peers into Channel, the response should be true if succeed
    response = await cli.channel_join(
        requestor=org1_admin,
        channel_name='businesschannel',
        peers=['peer0.org1.example.com', 'peer1.org1.example.com'],
        orderer='orderer.example.com')
    if response:
        print("Join channel successful")
    else:
        print("Join channel failed")
        exit(-1)

def main():
    loop = asyncio.get_event_loop()
    loop.run_until_complete(async_main())

if __name__ == '__main__':
    main()
```

But the response reported back is False. Really not sure about the cause and how to debug on the issue. Some help might be needed on how to correctly use the client to interact with the Fabric network.

**Comment by dexhunter** [comment]
Do you have configtxgen binaries in your PATH?

**Comment by znss1989** [comment]
Thank you for timely reply.
I guess no for the moment. Didn't see that in the instruction, I thought the docker images are all that are required.  Is there any suggested way to do that? Or should I install fabric and include all its binaries in the PATH?

**Comment by dexhunter** [comment]
you need to include binaries in the PATH. For example, `export PATH=$PATH:$PWD/fabric-bin` at the `fabric-sdk-py` directory

**Comment by znss1989** [comment]
Yes, I found the `NOTE` now. And your suggestion works for me. Thanks for helping.

**Comment by dexhunter** [comment]
great to hear, I am closing the issue now, let reopen or create a new issue if there are other problems. Thanks.

**Comment by Creazy-MR** [comment]
@znss1989  Dear Author ,i also have this problem when i try to run a test in fabric-sdk-py directory:
![error2](https://user-images.githubusercontent.com/59354418/168224937-765af61b-6e6a-47d4-a9ae-8bb7a179617f.png)
i have join the binaries in the PATH , bashrc:
how can i do,thank you!
