### ISSUE TITLE
How to register for chain code event using custom filter like latest block

### ISSUE THREAD

**Issue by Ram-srini** [hyperledger/fabric-sdk-py#89]
How to register for chain code event starting from the latest block. Something like below
channel_event_hub.registerChaincodeEvent(CC_NAME, 'invoked', start='latest',
            onEvent=_event_handler);

Where 'latest' corresponds to latest block number.

Or else how do i get the latest block number using fabric python sdk so that i can pass the latest block number to registerChaincodeEvent()

**Comment by Ram-srini** [comment]
@yeasy Please help to address this issue.

**Comment by dexhunter** [comment]
@Ram-srini A easy to find the number of block is through `query_info` function, you can find details [here](https://github.com/hyperledger/fabric-sdk-py/blob/master/docs/source/tutorial.md#41-basic-usage). For more advanced user, you can try to listen to an event hub and get the stream information. You can check the [`channel_eventhub.py`](https://github.com/hyperledger/fabric-sdk-py/blob/master/hfc/fabric/channel/channel_eventhub.py) for more information.
