### ISSUE TITLE
Missing sample.py file from the docs folder

### ISSUE THREAD

**Issue by kmehant** [hyperledger/fabric-sdk-py#92]
I can see that `sample.py` file is missing from the `docs/` folder.
Similarly, the link is broken at the read-the-docs too.

**Comment by kmehant** [comment]
@dexhunter it was added here eb536d7637e0e5119fe717220a72c3f7c4c3c2f3 Can I make the shift through a PR?

**Comment by dexhunter** [comment]
@kmehant The sample code is removed on purpose due to out-of-date, but we can fix the broken link.

**Comment by kmehant** [comment]
@dexhunter Shall we link to [e2e](https://github.com/hyperledger/fabric-sdk-py/blob/master/test/integration/e2e_test.py) test file in specific back as before or simply the complete test folder as a fix?

**Comment by dexhunter** [comment]
yep, I've created pr #93
